function[B] = cor_coeff_matrix(q)

    %%% function che in funzione delle variabili di giunto costruisce 
    %%% la matrice dei coefficienti delle forze di 
    %%% coriolis del manipolatore. IMPORTANTE va aggiornata
    %%% l'espressione ogni volta che vengono cambiate le caratteristiche
    %%% fisiche del manipolatore.

    % INPUT:
    % q:                    double [nx1] = variabili di giunto
    
    % OUTPUT:
    % B:                    double [nxn(n-1)/2] = matrice dei coefficienti delle forze di coriolis

    % estrazione componenti input
    % variabili di giunto
    q1 = q(1);
    q2 = q(2);
    q3 = q(3);
    q4 = q(4);
    q5 = q(5);
    
    % determinazione matrice dei coefficienti delle forze di coriolis
    B = [- (75509757275879979*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/18446744073709551616 - (1418544105622460673*sin(2*q2))/9223372036854775808 - (75509757275879979*sin(2*q2 + 2*q3 + 2*q4))/18446744073709551616 - (523187873391410013*sin(2*q2 + 2*q3))/9223372036854775808 - (1353*pi*sin(2*q2 + 2*q3 + q4 + q5))/40000 - (31119*pi*sin(2*q2 + 2*q3))/128000 - (28413*pi*sin(2*q2 + q3 + q4))/160000 - (28413*pi*sin(q3 + q4))/800000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + q5))/100000 - (9471*pi*sin(q3))/160000 - (4059*pi*sin(q4))/160000 - (4059*pi*sin(2*q2 + 2*q3 + q4))/32000 - (9471*pi*sin(2*q2 + q3 + q4 + q5))/200000 - (66297*pi*sin(2*q2 + q3))/80000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/400000 - (596673*pi*sin(2*q2))/800000 - (17589*pi*sin(2*q2 + 2*q3 + 2*q4))/800000, - (75509757275879979*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/18446744073709551616 - (75509757275879979*sin(2*q2 + 2*q3 + 2*q4))/18446744073709551616 - (523187873391410013*sin(2*q2 + 2*q3))/9223372036854775808 - (1353*pi*sin(2*q2 + 2*q3 + q4 + q5))/40000 - (31119*pi*sin(2*q2 + 2*q3))/128000 - (85239*pi*sin(2*q2 + q3 + q4))/800000 - (85239*pi*sin(q3 + q4))/800000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + q5))/100000 - (28413*pi*sin(q3))/64000 - (4059*pi*sin(q4))/160000 - (4059*pi*sin(2*q2 + 2*q3 + q4))/32000 - (9471*pi*sin(2*q2 + q3 + q4 + q5))/400000 - (28413*pi*sin(2*q2 + q3))/64000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/400000 - (9471*pi*sin(q3 + q4 + q5))/400000 - (17589*pi*sin(2*q2 + 2*q3 + 2*q4))/800000, - (75509757275879979*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/18446744073709551616 - (75509757275879979*sin(2*q2 + 2*q3 + 2*q4))/18446744073709551616 - (1353*pi*sin(2*q2 + 2*q3 + q4 + q5))/80000 - (85239*pi*sin(2*q2 + q3 + q4))/800000 - (85239*pi*sin(q3 + q4))/800000 - (1353*pi*sin(q4 + q5))/80000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + q5))/100000 - (12177*pi*sin(q4))/160000 - (12177*pi*sin(2*q2 + 2*q3 + q4))/160000 - (9471*pi*sin(2*q2 + q3 + q4 + q5))/400000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/400000 - (9471*pi*sin(q3 + q4 + q5))/400000 - (17589*pi*sin(2*q2 + 2*q3 + 2*q4))/800000, - (75509757275879979*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/18446744073709551616 - (1353*pi*sin(2*q2 + 2*q3 + q4 + q5))/80000 - (1353*pi*sin(q4 + q5))/80000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + q5))/200000 - (1353*pi*sin(q5))/200000 - (9471*pi*sin(2*q2 + q3 + q4 + q5))/400000 - (1353*pi*sin(2*q2 + 2*q3 + 2*q4 + 2*q5))/400000 - (9471*pi*sin(q3 + q4 + q5))/400000,                                                                                      0,                                                                                         0,                                                                    0,                                                                                         0,                                                                    0,                                                                    0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                   0, -(1353*pi*(28*sin(q3 + q4 + q5) + 126*sin(q3 + q4) + 525*sin(q3) + 30*sin(q4)))/800000, -(1353*pi*(14*sin(q3 + q4 + q5) + 63*sin(q3 + q4) + 10*sin(q4 + q5) + 45*sin(q4)))/400000, -(1353*pi*(7*sin(q3 + q4 + q5) + 5*sin(q4 + q5) + 2*sin(q5)))/200000, -(1353*pi*(14*sin(q3 + q4 + q5) + 63*sin(q3 + q4) + 10*sin(q4 + q5) + 45*sin(q4)))/400000, -(1353*pi*(7*sin(q3 + q4 + q5) + 5*sin(q4 + q5) + 2*sin(q5)))/200000, -(1353*pi*(7*sin(q3 + q4 + q5) + 5*sin(q4 + q5) + 2*sin(q5)))/200000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                   0,                                                               -(4059*pi*sin(q4))/80000,                                             -(1353*pi*(2*sin(q4 + q5) + 9*sin(q4)))/80000,                       -(1353*pi*(5*sin(q4 + q5) + 2*sin(q5)))/200000,                                             -(1353*pi*(2*sin(q4 + q5) + 9*sin(q4)))/80000,                       -(1353*pi*(5*sin(q4 + q5) + 2*sin(q5)))/200000,                       -(1353*pi*(5*sin(q4 + q5) + 2*sin(q5)))/200000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                   0,                                             (1353*pi*(sin(q4 + q5) + 3*sin(q4)))/40000,                                                                                         0,                                            -(1353*pi*sin(q5))/100000,                                                                                         0,                                            -(1353*pi*sin(q5))/100000,                                            -(1353*pi*sin(q5))/100000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                   0,                                          (1353*pi*(5*sin(q4 + q5) + 2*sin(q5)))/200000,                                                                  (1353*pi*sin(q5))/100000,                                                                    0,                                                                  (1353*pi*sin(q5))/100000,                                                                    0,                                                                    0];
 % fine matrice
                       
end